baseURL = 'https://blog.enochyu.com'
languageCode = 'en-US'
title = "Enoch Yu's Blog"

defaultContentLanguage = "en"
defaultContentLanguageInSubdir = false
enableRobotsTXT = true

[params]
  author = "Enoch Yu"
  avatar = "/avatar.png"
  mainSections = ["posts"]
  favicon = "/favicon/favicon.ico"
  math = true

[params.social]
  website = "https://enochyu.com/"
  youtube = "https://www.youtube.com/channel/UCCnkn0YRKStraznc7kuICRg"
  github = "https://github.com/enochyu-official"

[params.comments]
  enabled = true
  provider = "giscus"

[taxonomies]
  category = "categories"
  tag      = "tags"

[markup]
  [markup.tableOfContents]
    startLevel = 2
    endLevel = 4
    ordered = false
  [markup.highlight]

[[menu.main]]
  name = "Home"
  url = "/"
  weight = 1

[[menu.main]]
  name = "Archives"
  url = "/archives/"
  weight = 2

